const router= require('express').Router()
const {eduCreate,getBlog,allBlog,blogUpdate,blogDelete,
    elementById,blogById,blogCreate,getBlogs,getMainAll,
    aboutCreate,getAllPhrase,phraseById,getAllAbout,
    aboutById,aboutDelete,aboutUpdate,phraseDelete,
    getAllSlider,sliderById,sliderDelete,sliderUpdate,phraseUpdate,phraseCreate}=require('../controller/blogController')
const upload= require('../middleware/fileUploads')
const {isAuth} = require('../middleware/auth')
const {admin,superAdmin} = require('../middleware/admin')

router.get('/',getMainAll)
router.route('/edu')
    .post(upload.single('image'),isAuth,admin, eduCreate)
    .get(isAuth,admin,getAllSlider)
router.route('/blog',)
    .post(upload.single('image'),isAuth,admin,blogCreate)
    .get(getBlogs)
router.route('/about',)
    .post(upload.single('image'),isAuth,admin, aboutCreate)
    .get(isAuth,admin,getAllAbout)
router.route('/phrase')
    .post(isAuth,admin,phraseCreate)
    .get(isAuth,admin,getAllPhrase)
router.route('/phrase/:id')
    .get(isAuth,admin,phraseById)
    .delete(isAuth,admin,phraseDelete)
    .put(isAuth,admin,phraseUpdate)
router.get('/blog/all',allBlog)
router.get('/single',getBlog)
router.get('/blog/edit/:id',isAuth,admin,blogById)
router.route('/blog/:id')
    .get(elementById)
    .delete(isAuth,admin,blogDelete)
    .put(isAuth,admin,upload.single('image'),blogUpdate)
router.route('/about/:id')
    .get(isAuth,admin,aboutById)
    .delete(isAuth,admin,aboutDelete)
    .put(isAuth,upload.single('image'),admin,aboutUpdate)
router.route('/slider/:id')
    .get(isAuth,admin,sliderById)
    .delete(isAuth,admin,sliderDelete)
    .put(isAuth,upload.single('image'),admin,sliderUpdate)
module.exports=router