const router= require('express').Router()
const {eduCreate,getBlog,allBlog,blogUpdate,blogDelete,elementById,blogById,blogCreate,getBlogs,getMainAll,aboutCreate,phraseCreate}=require('../controller/blogController')
const upload= require('../middleware/fileUploads')

router.get('/',getMainAll)
router.route('/edu')
    .post(upload.single('image'), eduCreate)

router.route('/blog',)
    .post(upload.single('image'),blogCreate)
    .get(getBlogs)
router.route('/about',)
    .post(upload.single('image'), aboutCreate)
router.route('/phrase')
    .post(upload.single('image'), phraseCreate)
router.get('/blog/all',allBlog)
router.get('/single',getBlog)
router.get('/blog/edit/:id',blogById)
router.route('/blog/:id')
    .get(elementById)
    .delete(blogDelete)
    .put(upload.single('image'),blogUpdate)
module.exports=router