const router=require('express').Router()
const {courseCreate, getAll, getCourse, elementDelete}=require('../controller/courseController')
const upload = require('../middleware/fileUploads')
router.route('/course')
    .get(getAll)
    .post(upload.single('image'), courseCreate)
router.route('/course/:id')
    .delete(elementDelete)
router.get('/courses/:category', getCourse)
module.exports=router