const router=require('express').Router()
const {courseCreate, elementById,courseUpdate,courseByID, getAll, getCourse, elementDelete}=require('../controller/courseController')
const {searchCourse,getAllData} = require('../controller/search')
const upload = require('../middleware/fileUploads')
const {isAuth} = require('../middleware/auth')
const {admin,superAdmin} = require('../middleware/admin')
router.route('/course')
    .get(getAll)
    .post(isAuth,admin,upload.single('image'), courseCreate)
router.route('/course/:id')
    .delete(isAuth,admin,elementDelete)
    .get(elementById)
    .put(upload.single('image'),isAuth,admin,courseUpdate)
router.get('/courses/:category', getCourse)
router.get('/course/edit/:id',isAuth,admin,courseByID)
router.get('/search', isAuth,admin, searchCourse)
router.get('/admin',isAuth,getAllData)
module.exports=router